check for missing -d argument

diff --git a/install b/install
--- a/install
+++ b/install
@@ -77,6 +77,11 @@ if [[ ! -e "$INSTALL_DIR" ]] ; then
   exit 1
 fi
 
+if [[ -z ${INSTALL_DIR} ]]; then
+  echo "Error: missing install directory (-d) value"
+  exit 1
+fi
+
 if [[ -z ${MIRROR} ]]; then
   echo "Error: missing mirror (-m) value"
   exit 1
