Image description (-D) is a require arg

diff --git a/install b/install
--- a/install
+++ b/install
@@ -17,17 +17,18 @@ cat <<EOF
 Install and modify Ubuntu in a given directory using a given mirror.
 
 Usage:
-  $0 -r <RELEASE> -d <INSTALL_DIR> -m <MIRROR> -i <IMAGE_NAME> -p <NAME> -u <DOCS>
+  $0 -r <RELEASE> -d <INSTALL_DIR> -m <MIRROR> -i <IMAGE_NAME> -p <NAME> -D <DESC> -u <DOCS>
 
 Example:
-  $0 -r trusty -d /mnt/chroot -m http://archive.ubuntu.com/ubuntu/ -i lx-ubuntu-14.04 -p "Ubuntu 14.04 LX Brand" -u https://docs.joyent.com/images/lx-brand-beta
+  $0 -r trusty -d /mnt/chroot -m http://archive.ubuntu.com/ubuntu/ -i lx-ubuntu-14.04 -p "Ubuntu 14.04 LX Brand" -D "Ubuntu 14.04 lx 64-bit lx-brand image." -u https://docs.joyent.com/images/lx-brand-beta
 
 OPTIONS:
   -r The desired release (e.g "trusty")
   -d A path to the install directory
   -m A URL for the desired archive mirror
   -i The name of the image. This is used for naming the tarball. 
-  -p The proper name of the image. Use quotes. This is used in the MOTD and /etc/product file. 
+  -p The proper name of the image. Use quotes. This is used in the MOTD and /etc/product file.
+  -D A description for the image. This is used in the image manifest and the /etc/product file.
   -u A URL to the image docs [optional]
   -h Show this message
 
@@ -39,9 +40,10 @@ INSTALL_DIR=
 MIRROR=
 IMAGE_NAME=
 NAME=
+DESC=
 DOCS=
 
-while getopts "hr:d:m:i:p:u:" OPTION
+while getopts "hr:d:m:i:p:D:u:" OPTION
 do
   case $OPTION in
     h)
@@ -62,6 +64,9 @@ do
       ;;
     p)
       NAME=${OPTARG}
+      ;;
+    D)
+      DESC=${OPTARG}
       ;;
     u)
       DOCS=${OPTARG}
@@ -105,6 +110,11 @@ fi
 
 if [[ -z ${NAME} ]]; then
   echo "Error: missing proper name (-p) value"
+  exit 1
+fi
+
+if [[ -z ${DESC} ]]; then
+  echo "Error: missing image description (-D) value"
   exit 1
 fi
 
